# Generated by Django 4.0 on 2021-12-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personna',
            name='adress_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personna',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personna',
            name='postcode',
            field=models.IntegerField(),
        ),
    ]
